spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flopezhu/bootcamp.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: master
  application:
    name: bootcamp-config-server
  security:
    user:
      name: root
      password: admin

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
      health:
        show-details: always

#por for config server 8888
server:
  port: 8888